# Generated by Django 5.2.17 on 2026-08-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_number', models.CharField(max_length=10, unique=True)),
                ('origin', models.CharField(max_length=400)),
                ('destination', models.CharField(max_length=400)),
                ('recipient', models.CharField(max_length=400)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('intransit', 'INTRANSIT'), ('delivered', 'DELIVERED')], default='PENDING', max_length=20)),
            ],
        ),
    ]
