# Generated by Django 5.2.17 on 2026-08-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_historicalpackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='destination',
            new_name='destiny',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='guide_number',
            new_name='id_guide',
        ),
    ]
